// <auto-generated />
namespace CRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class table_programador : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(table_programador));
        
        string IMigrationMetadata.Id
        {
            get { return "201612282220478_table_programador"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
